In [1]:
import pandas as pd
import numpy as np

In [2]:
predated_companies = pd.read_csv('predated_companies.csv')

In [3]:
predated_companies

,entity_urn,updated_at,website,ownership_status,headcount,founding_date,twitter_follower_count,linkedin_follower_count,linkedin_url_harmonic,funding_total,...,emp_delta_12m,adj_emp_delta_12m,investor_1,investor_2,investor_3,Prior VC Backed Founder_count,Deep Technical Background_count,Prior Exit_count,Elite Industry Experience_count,emp_highlight_count
0,urn:harmonic:company:4202310,2024-11-30,"{'domain': 'trybond.com', 'is_broken': False, ...",NaN,15,2020-01-01,NaN,1122,https://linkedin.com/company/trybond,0.00000,...,-3.000000,-2.550000,0,0,0,0,0,0,0,1
1,urn:harmonic:company:1919666,2024-11-30,"{'domain': 'dovetail.co', 'is_broken': True, '...",ACQUIRED_OR_MERGED,7,2010-01-01,147.0,641,https://linkedin.com/company/dovetail-dental-s...,0.00000,...,-1.000000,-0.800000,0,0,0,0,0,0,0,0
2,urn:harmonic:company:725441,2024-08-16,"{'domain': 'waldron.app', 'is_broken': True, '...",OUT_OF_BUSINESS,7,2021-01-01,NaN,181,https://linkedin.com/company/wilde-xyz,0.00000,...,1.000000,0.883333,0,0,0,1,0,0,0,2
3,urn:harmonic:company:3609920,2024-11-12,"{'domain': 'ventture.com', 'is_broken': False,...",NaN,15,2021-01-01,188.0,24490,https://linkedin.com/company/ventture,0.00000,...,-5.000000,-4.250000,0,0,0,0,0,0,0,0
4,urn:harmonic:company:8762211,2024-10-08,"{'domain': 'venda-search.com', 'is_broken': Tr...",NaN,10,2018-01-01,NaN,15690,https://linkedin.com/company/venda-search,0.00000,...,-0.836817,-0.775958,0,0,0,0,0,0,0,0
5,urn:harmonic:company:1386978,2024-11-21,"{'domain': 'frwk.com.br', 'is_broken': True, '...",NaN,401,2009-01-01,NaN,87983,https://linkedin.com/company/frameworkdigital,0.00000,...,0.000000,0.000000,0,0,0,0,0,0,1,3
6,urn:harmonic:company:1443055,2024-10-24,"{'domain': 'thirdsidesolutions.com', 'is_broke...",NaN,4,2010-01-01,343.0,54,https://linkedin.com/company/thirdside-solutio...,0.42185,...,-2.000000,-2.000000,0,0,0,0,0,0,0,3
7,urn:harmonic:company:1885627,2024-11-12,"{'domain': 'skillcloud.s407.sureserver.com', '...",NaN,37,2015-01-01,21.0,329,https://linkedin.com/company/skillcloud-consul...,0.00000,...,21.000000,21.000000,0,0,0,0,0,0,0,4
8,urn:harmonic:company:4463262,2024-10-26,"{'domain': 'unitalent.com.cn', 'is_broken': Tr...",NaN,1681,2007-01-01,NaN,3314,https://linkedin.com/company/uni,0.00000,...,364.985311,285.510155,0,0,0,0,0,0,0,0
9,urn:harmonic:company:4487243,2024-08-17,"{'domain': 'mama-bears.fr', 'is_broken': True,...",NaN,6,2019-01-01,NaN,1859,https://linkedin.com/company/mama-bears-solos-...,0.00000,...,1.324620,1.103850,0,0,0,0,0,0,0,0
10,urn:harmonic:company:4489582,2024-08-09,"{'domain': 'immersively.live', 'is_broken': Tr...",NaN,27,2021-01-01,NaN,106,https://linkedin.com/company/immersive-inc,0.00000,...,2.000000,1.843636,0,0,0,0,0,0,0,0
11,urn:harmonic:company:4864635,2024-11-17,"{'domain': 'dvphilippines.com', 'is_broken': T...",NaN,870,2012-01-01,1262.0,25737,https://linkedin.com/company/d&v-philippines,0.00000,...,79.000000,79.000000,0,0,0,0,0,0,4,4
12,urn:harmonic:company:5344312,2024-11-21,"{'domain': 'mainlineprivatewealth.com', 'is_br...",ACQUIRED_OR_MERGED,7,2011-01-01,15.0,71,https://linkedin.com/company/mainline-private-...,0.00000,...,-18.000000,-15.300000,0,0,0,0,0,0,0,0
13,urn:harmonic:company:10845360,2024-10-24,"{'domain': 'felixcomunity.carrd.co', 'is_broke...",NaN,7,2021-01-01,NaN,99,https://linkedin.com/company/felixpe,0.00000,...,1.000000,0.850000,0,0,0,0,0,0,0,0
14,urn:harmonic:company:15117973,2024-08-20,"{'domain': 'alphagroup-uk.com', 'is_broken': T...",NaN,118,2012-01-01,NaN,244,https://linkedin.com/company/alpha-group-uk,0.00000,...,26.050870,18.655784,0,0,0,0,0,0,0,0
15,urn:harmonic:company:4323919,2024-10-01,"{'domain': 'joinmochi.com', 'is_broken': False...",PRIVATE,155,2022-02-01,208.0,8364,https://linkedin.com/company/mochihealth,1.15000,...,100.000000,85.000000,0,0,0,0,0,0,0,11

In [4]:
final_features = ['linkedin_follower_growth_1m',
 'current_max_ratio',
 'earliest_valid_month',
 'headcount_growth_1m',
 'headcount_volatility_score',
 'headcount_growth_3m',
 'employee_highlight_top_institution_experience_count',
 'years_since_funding',
 'trailing_growth_max',
 'linkedin_follower_growth_6m',
 'headcount_growth_6m',
 'emp_highlight_count',
 'trailing_growth_std',
 'linkedin_follower_count_max',
 'emp_role_entropy',
 'linkedin_follower_count_0m',
 'trailing_growth_avg',
 'United States Sales',
 'linkedin_follower_growth_3m',
 'linkedin_follower_count_volatility',
 'headcount_0m',
 'adj_emp_delta_6m',
 'investor_1',
 'United States Engineering',
 'twitter_follower_count_volatility',
 'business_function_entropy',
 'twitter_follower_count_max',
 'employee_highlight_Prior VC Backed Executive',
 'twitter_follower_count_0m',
 'years_since_founding',
 'employee_highlight_seasoned_count',
 'headcount_concavity',
 'Elite Industry Experience_count']

In [5]:
missing_features = [f for f in final_features if f not in predated_companies.columns]

In [6]:
missing_features

['current_max_ratio',
 'earliest_valid_month',
 'headcount_volatility_score',
 'employee_highlight_top_institution_experience_count',
 'trailing_growth_max',
 'trailing_growth_std',
 'linkedin_follower_count_max',
 'emp_role_entropy',
 'trailing_growth_avg',
 'linkedin_follower_count_volatility',
 'twitter_follower_count_volatility',
 'business_function_entropy',
 'twitter_follower_count_max',
 'employee_highlight_Prior VC Backed Executive',
 'employee_highlight_seasoned_count']

In [7]:
predated_companies['updated_at']

0     2024-11-30
1     2024-11-30
2     2024-08-16
3     2024-11-12
4     2024-10-08
5     2024-11-21
6     2024-10-24
7     2024-11-12
8     2024-10-26
9     2024-08-17
10    2024-08-09
11    2024-11-17
12    2024-11-21
13    2024-10-24
14    2024-08-20
15    2024-10-01
Name: updated_at, dtype: object

In [8]:
predated_companies.filter(like='headcount_')

,headcount_0m,headcount_1m,headcount_2m,headcount_3m,headcount_4m,headcount_5m,headcount_6m,headcount_7m,headcount_8m,headcount_9m,...,headcount_growth_trailing_3m_5m,headcount_growth_trailing_3m_6m,headcount_growth_trailing_3m_7m,headcount_growth_trailing_3m_8m,headcount_growth_trailing_3m_9m,headcount_growth_trailing_3m_10m,headcount_growth_trailing_3m_11m,headcount_growth_trailing_3m_12m,headcount_monotonicity,headcount_concavity
0,15,16,16,18,19,18,18.0,19,19,20,...,0.947368,0.900000,0.904762,0.950000,1.111111,1.166667,1.176471,1.058824,0.250000,0.272727
1,7,8,8,8,8,8,8.0,8,8,8,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.909091
2,7,6,6,6,6,6,6.0,6,6,6,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.083333,1.000000
3,15,15,15,15,16,6,6.0,5,4,20,...,1.500000,0.300000,0.250000,0.200000,1.000000,1.000000,1.052632,1.176471,0.416667,0.636364
4,10,10,10,10,10,12,14.0,14,15,17,...,0.800000,0.823529,0.823529,NaN,NaN,NaN,NaN,NaN,0.000000,0.714286
5,401,404,404,399,392,378,383.0,394,394,394,...,0.959391,0.972081,0.989950,0.982544,0.982544,0.973105,0.952494,NaN,0.333333,0.636364
6,4,5,5,5,6,6,6.0,6,6,6,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.818182
7,37,16,16,16,16,16,16.0,16,16,16,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.888889,0.083333,1.000000
8,1681,1685,1685,1685,1687,1687,1689.0,1694,1695,1701,...,0.995280,0.992945,0.995300,NaN,NaN,NaN,NaN,NaN,0.000000,0.714286
9,6,6,6,6,6,6,6.0,6,6,6,...,1.000000,1.000000,0.857143,0.750000,NaN,NaN,NaN,NaN,0.000000,1.000000
10,27,25,25,25,25,25,25.0,25,25,25,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.083333,1.000000
11,870,909,909,878,870,870,870.0,843,829,825,...,1.049457,1.054545,1.026797,1.032379,1.042984,1.048531,1.049673,1.033987,0.916667,0.272727
12,7,25,25,25,25,25,25.0,25,25,25,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000,0.909091
13,7,7,7,7,7,6,6.0,6,6,6,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.250000,0.909091
14,118,118,118,118,118,118,118.0,118,118,118,...,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000
15,155,142,142,142,142,136,125.0,109,95,86,...,1.431579,1.453488,1.362500,1.727273,1.563636,1.568627,1.375000,1.375000,0.916667,0.363636

In [9]:
aug_companies = predated_companies[(predated_companies['updated_at'] >= '2024-08-01') & (predated_companies['updated_at'] <= '2024-08-31')].reset_index(drop=True).copy()

In [10]:
aug_companies

,entity_urn,updated_at,website,ownership_status,headcount,founding_date,twitter_follower_count,linkedin_follower_count,linkedin_url_harmonic,funding_total,...,emp_delta_12m,adj_emp_delta_12m,investor_1,investor_2,investor_3,Prior VC Backed Founder_count,Deep Technical Background_count,Prior Exit_count,Elite Industry Experience_count,emp_highlight_count
0,urn:harmonic:company:725441,2024-08-16,"{'domain': 'waldron.app', 'is_broken': True, '...",OUT_OF_BUSINESS,7,2021-01-01,NaN,181,https://linkedin.com/company/wilde-xyz,0.0,...,1.00000,0.883333,0,0,0,1,0,0,0,2
1,urn:harmonic:company:4487243,2024-08-17,"{'domain': 'mama-bears.fr', 'is_broken': True,...",NaN,6,2019-01-01,NaN,1859,https://linkedin.com/company/mama-bears-solos-...,0.0,...,1.32462,1.103850,0,0,0,0,0,0,0,0
2,urn:harmonic:company:4489582,2024-08-09,"{'domain': 'immersively.live', 'is_broken': Tr...",NaN,27,2021-01-01,NaN,106,https://linkedin.com/company/immersive-inc,0.0,...,2.00000,1.843636,0,0,0,0,0,0,0,0
3,urn:harmonic:company:15117973,2024-08-20,"{'domain': 'alphagroup-uk.com', 'is_broken': T...",NaN,118,2012-01-01,NaN,244,https://linkedin.com/company/alpha-group-uk,0.0,...,26.05087,18.655784,0,0,0,0,0,0,0,0

In [11]:
headcount_cols = [f'headcount_{i}m' for i in range(0,19)]

In [12]:
def shift_headcount(row, shift):
    max_shift = 18 - shift
    trailing_shift = 12 - shift
    for i in range(0, max_shift + 1): 
        row[f"headcount_{i+shift}m"] = row[f"headcount_{i}m"]
        row[f"linkedin_follower_count_{i+shift}m"] = row[f"linkedin_follower_count_{i}m"]
        row[f"twitter_follower_count_{i+shift}m"] = row[f"twitter_follower_count_{i}m"]

    for i in range(0, trailing_shift + 1): 
        row[f"headcount_growth_trailing_3m_{i+shift}m"] = row[f"headcount_growth_trailing_3m_{i}m"]

    for i in range(0, shift):
        row[f"headcount_{i}m"] = np.nan
        row[f"headcount_growth_trailing_3m_{i}m"] = np.nan
        row[f"linkedin_follower_count_{i}m"] = np.nan
        row[f"twitter_follower_count_{i}m"] = np.nan
    return row

aug_companies = aug_companies.apply(shift_headcount, args=(4,), axis=1)

In [13]:
oct_companies = predated_companies[(predated_companies['updated_at'] >= '2024-10-01') & (predated_companies['updated_at'] <= '2024-10-31')].reset_index(drop=True).copy()

In [14]:
oct_companies[headcount_cols]

,headcount_0m,headcount_1m,headcount_2m,headcount_3m,headcount_4m,headcount_5m,headcount_6m,headcount_7m,headcount_8m,headcount_9m,headcount_10m,headcount_11m,headcount_12m,headcount_13m,headcount_14m,headcount_15m,headcount_16m,headcount_17m,headcount_18m
0,10,10,10,10,10,12,14.0,14,15,17,17,NaN,10.836817,NaN,NaN,NaN,NaN,NaN,NaN
1,4,5,5,5,6,6,6.0,6,6,6,6,6.0,6.000000,6.0,6.0,6.0,6.0,6.0,6.0
2,1681,1685,1685,1685,1687,1687,1689.0,1694,1695,1701,1702,NaN,1316.014689,NaN,NaN,NaN,NaN,NaN,NaN
3,7,7,7,7,7,6,6.0,6,6,6,6,6.0,6.000000,6.0,6.0,6.0,6.0,6.0,3.0
4,155,142,142,142,142,136,125.0,109,95,86,80,55.0,55.000000,51.0,40.0,40.0,37.0,30.0,28.0

In [15]:
oct_companies = oct_companies.apply(shift_headcount, args=(2,), axis=1)

In [16]:
oct_companies[headcount_cols]

,headcount_0m,headcount_1m,headcount_2m,headcount_3m,headcount_4m,headcount_5m,headcount_6m,headcount_7m,headcount_8m,headcount_9m,headcount_10m,headcount_11m,headcount_12m,headcount_13m,headcount_14m,headcount_15m,headcount_16m,headcount_17m,headcount_18m
0,NaN,NaN,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
1,NaN,NaN,4,5,4,5,4,5,4,5,4,5,4,5,4,5,4,5,4
2,NaN,NaN,1681,1685,1681,1685,1681,1685,1681,1685,1681,1685,1681,1685,1681,1685,1681,1685,1681
3,NaN,NaN,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
4,NaN,NaN,155,142,155,142,155,142,155,142,155,142,155,142,155,142,155,142,155

In [17]:
nov_companies = predated_companies[(predated_companies['updated_at'] >= '2024-11-01') & (predated_companies['updated_at'] <= '2024-11-30')].reset_index(drop=True).copy()

In [18]:
nov_companies = nov_companies.apply(shift_headcount, args=(1,), axis=1)

In [19]:
nov_companies[headcount_cols]

,headcount_0m,headcount_1m,headcount_2m,headcount_3m,headcount_4m,headcount_5m,headcount_6m,headcount_7m,headcount_8m,headcount_9m,headcount_10m,headcount_11m,headcount_12m,headcount_13m,headcount_14m,headcount_15m,headcount_16m,headcount_17m,headcount_18m
0,NaN,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
1,NaN,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
2,NaN,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
3,NaN,401,401,401,401,401,401,401,401,401,401,401,401,401,401,401,401,401,401
4,NaN,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37
5,NaN,870,870,870,870,870,870,870,870,870,870,870,870,870,870,870,870,870,870
6,NaN,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7

In [20]:
predated_companies_rehashed = pd.concat([aug_companies, oct_companies, nov_companies])

In [21]:
predated_companies_rehashed = predated_companies_rehashed.drop(columns=['headcount_18m', 'headcount_growth_trailing_3m_12m',
                                          "linkedin_follower_count_18m", "twitter_follower_count_18m"])

In [22]:
predated_companies_rehashed.to_csv('predated_companies_rehashed.csv', index=False)